enum XZONERADc
{
    SERVER_SEND_MAIN_DATA = 178834,
    SERVER_SEND_MAIN_DATA_TO_CLIENT,
    SERVER_SEND_MAIN_DATA_RESIST_BAKPACK,
    SERVER_SEND_MAIN_DATA_RESIST_HELM,
    SERVER_SEND_MAIN_DATA_RESIST_VEST,
    SERVER_SEND_MAIN_DATA_RESIST_BODY,
    SERVER_SEND_MAIN_DATA_RESIST_FEET,
    SERVER_SEND_MAIN_DATA_RESIST_GLOVES,
    SERVER_SEND_MAIN_DATA_RESIST_LEGS,
    SERVER_SEND_MAIN_DATA_RESIST_GAS_MASK,
}