enum RADRPCc
{
	// Client -> Server
	RPC_SET_INNER_RAD = 98165,
	RPC_SET_CONSUME_FILTER_RAD,
	RPC_PLAYER_HAS_RAD,
	RPC_PLAYER_USE_ANTIRAD,
	RPC_PLAYER_GET_OVERDOZE,
	RPC_PLAYER_GET_ALCOHOL,

	// Server -> Client
	RPC_SEND_USE_ANTIRAD,
	RPC_SEND_RAD_LOAD,
}